name: Deploy to "dist" branch
on:
  push:
    branches:
      - master
jobs:
  deploy-to-dist-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deploy
        run: |
          # Split "dist" directory into a local "dist" branch.
          git subtree split --prefix dist -b dist
          # Force push the new "dist" branch on top of the remote "dist" branch.
          git push --force origin dist:dist
          # delete the local "dist" branch.
          git branch -D dist
